# Generated by Django 5.1.3 on 2025-01-04 00:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chamba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('empleado', 'Empleado'), ('empleador', 'Empleador')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.CharField(db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Correo inválido', regex='^\\S+@\\S+\\.\\S+$')])),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=15)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('tipo_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.chamba')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftoCarnetFront', models.ImageField(blank=True, null=True, upload_to='documents/carnet/')),
                ('ftoCarnetBack', models.ImageField(blank=True, null=True, upload_to='documents/carnet/')),
                ('certAntecedentes', models.FileField(blank=True, null=True, upload_to='documents/antecedentes/')),
                ('ftoPersonal', models.ImageField(blank=True, null=True, upload_to='documents/personal/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Califications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(blank=True, null=True)),
                ('calificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificado', to='Tasks.personal')),
                ('calificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificador', to='Tasks.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=99)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Habilidades', to='Tasks.category')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('costo', models.IntegerField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='Tasks.personal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_solicited', to='Tasks.personal')),
                ('habilidades_requeridas', models.ManyToManyField(related_name='tareas_requeridas', to='Tasks.skill')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.location')),
            ],
        ),
    ]
